const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
const GET_ALL_DIETS = 'GET_ALL_DIETS';
const GET_RECIPES_ID = 'GET_RECIPES_ID';
const GET_RECIPES_NAME = 'GET_RECIPES_NAME';
const FILTER_TYPE_DIETS = 'FILTER_TYPE_DIETS';
const ORDER_ALPHA = 'ORDER_ALPHA';
const ORDER_SCORE = 'CHANGE_PAGE';
const CREATE_RECIPE = 'CREATE_RECIPE';
const DELETE_RECIPE = 'DELETE_RECIPE';
const CREATE_OR_NOT = 'CREATE_OR_NOT';
const ORDERLESS_FIVE = 'ORDERLESS_FIVE';

module.exports = {
    GET_ALL_RECIPES,
    GET_ALL_DIETS,
    GET_RECIPES_ID,
    GET_RECIPES_NAME,
    FILTER_TYPE_DIETS,
    ORDER_ALPHA,
    ORDER_SCORE,
    CREATE_RECIPE,
    DELETE_RECIPE,
    CREATE_OR_NOT,
    ORDERLESS_FIVE
}
